"""create job_postings table

Revision ID: 233cabd534d2
Revises: d98c94e6ea55
Create Date: 2026-09-05 12:43:58.119509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233cabd534d2'
down_revision: Union[str, None] = 'd98c94e6ea55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('description_snippet', sa.String(length=1000), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_external_id'), 'job_postings', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_external_id'), table_name='job_postings')
    op.drop_table('job_postings')
    # ### end Alembic commands ###
