"""create job_roles and job_role_skills tables

Revision ID: aa60acbdf700
Revises: da26f00361f8
Create Date: 2026-09-03 15:08:04.010605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa60acbdf700'
down_revision: Union[str, None] = 'da26f00361f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_role_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_role_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_role_skills_job_role_id'), 'job_role_skills', ['job_role_id'], unique=False)
    op.create_index(op.f('ix_job_role_skills_skill_id'), 'job_role_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_role_skills_skill_id'), table_name='job_role_skills')
    op.drop_index(op.f('ix_job_role_skills_job_role_id'), table_name='job_role_skills')
    op.drop_table('job_role_skills')
    op.drop_table('job_roles')
    # ### end Alembic commands ###
